// AUTO-GENERATED by scripts/generate-hero-manifest.mjs
// Do not edit manually.

export const HERO_IMAGES = [
  "/Hero/Hero_1.png",
  "/Hero/Hero_2.png",
  "/Hero/Hero_3.png",
  "/Hero/Hero_4.png",
  "/Hero/Hero_5.png",
  "/Hero/Hero_6.jpeg",
  "/Hero/Hero_7.jpeg"
] as const;
export type HeroImage = (typeof HERO_IMAGES)[number];

export const ABOUT_HERO_IMAGES = [
  "/Hero/About/image.png",
  "/Hero/About/IMG_7586.png"
] as const;

export const CONTACT_HERO_IMAGES = [] as const;

export const MEMBERS_HERO_IMAGES = [
  "/Hero/Members/A3B63677-9A9D-417E-A854-09F132AEA1A6_1_105_c.jpeg.png",
  "/Hero/Members/IMG_7698.png"
] as const;

export const PROJECTS_HERO_IMAGES = [
  "/Hero/Projects/CleanShot 2025-12-03 at 14.08.03@2x.png",
  "/Hero/Projects/IMG_7693.png"
] as const;

export const SEMINARS_HERO_IMAGES = [
  "/Hero/Seminars/22AFD380-A4DF-4A81-8B2B-567464437738_1_201_a.png",
  "/Hero/Seminars/553E48D8-3236-4A92-B0F1-ACFD785FF0C5_1_105_c.jpeg.png",
  "/Hero/Seminars/712C244E-DBCD-4619-AE05-D571053EB826_1_105_c.jpeg",
  "/Hero/Seminars/CleanShot 2025-11-24 at 19.57.44@2x.png"
] as const;
